<?php
use Laminas\Form\Element\Select;

// Set up pagination.
$pagination = $this->pagination(null, $totalCount, $page, $perPage);
$fragment = 'resources-linked';
$pagination->setFragment($fragment);
$plugins = $this->getHelperPluginManager();
$thumbnail = $plugins->get('thumbnail');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$siteSlug = isset($site) ? $site->slug() : null;
$hyperlink = $plugins->get('hyperlink');
$defaultThumbnail = sprintf('<img loading="lazy" src="%1$s" title="%2$s"/>', $assetUrl('thumbnails/default.png', 'Omeka', true), $translate('No media'));

// Set up locale.
$valueLang = null;
if ($this->status()->isSiteRequest()) {
    $lang = $this->lang();
    $filterLocale = (bool) $this->siteSetting('filter_locale_values');
    $valueLang = $filterLocale ? [$lang, ''] : null;
}

// Set up resource property select.
$labelMap = [
    'items' => 'Items', // @translate
    'item_sets' => 'Item sets', // @translate
    'media' => 'Media', // @translate
];
$resourcePropertiesSelect = new Select('resource_property');
$resourcePropertiesSelect->setValue($resourceProperty);
$resourcePropertiesSelect->setAttributes([
    'id' => 'resource-property-select',
    'data-url' => $this->url(null, [], true),
    'data-fragment' => $fragment,
]);
$valueOptions = [];
foreach ($resourcePropertiesAll as $type => $resourceProperties) {
    if (!$resourceProperties) {
        continue;
    }
    $valueOptions[$type] = [
        'label' => $labelMap[$type],
        'options' => [sprintf('%s:', $type) => sprintf('%s: All', $labelMap[$type])],
    ];
    foreach ($resourceProperties as $resourceProperty) {
        $label = $resourceProperty['label_is_translatable']
            ? $this->translate($resourceProperty['label'])
            : $resourceProperty['label'];

        $valueOptions[$type]['options'][] = [
            'value' => $resourceProperty['compound_id'],
            'label' => sprintf('%s: %s', $labelMap[$type], $label),
            'attributes' => [
                'title' => $resourceProperty['term'],
            ],
        ];
    }
}
$resourcePropertiesSelect->setValueOptions($valueOptions);
$headingTerm = $this->siteSetting('browse_heading_property_term');
?>
<div id="linked-resources">

<div class="linked-header">
    <div id="linked-filter">
        <label>
            <?php echo $this->translate('Filter by resource type and property:'); ?>
            <?php echo $this->formElement($resourcePropertiesSelect); ?>
        </label>
    </div>
</div>

<?php foreach ($subjectValues as $values): ?>
    <?php
    $caption = sprintf(
        $this->translate('%s with "%s: %s"'),
        $this->translate($labelMap[$resourceType]),
        $values[0]['property_alternate_label'] ?? $this->translate($values[0]['property_label']),
        $objectResource->displayTitle()
    );
    ?>

    <div class="linked-resource-accordion accordion__container">
        <h6 class="linked-resource-heading accordion__heading">
            <button class="linked-resource-property accordion__trigger"
                    type="button"
                    aria-expanded="false"
                    aria-controls="accordion__panel-<?php echo $values[0]['property_id']; ?>"
                    id="accordion-<?php echo $values[0]['property_id']; ?>">
                <span class="accordion__title">
                    <?php echo $this->escapeHtml($caption); ?>
                    <span class="accordion__icon o-icon-chevron-down"></span>
                </span>
            </button>
        </h6>

        <div class="linked-resource-property__panel accordion__panel"
            id="accordion__panel-<?php echo $values[0]['property_id']; ?>"
            role="region"
            aria-labelledby="accordion-<?php echo $values[0]['property_id']; ?>">
            <div class="linked-resources">
            <ul class="linked-resource-list-grid">
            <?php foreach ($values as $value) :

                $resource = $value['val']->resource();
                $vals = $resource -> values();
                $resourceUrl = isset($site) ? $resource->siteUrl($siteSlug) : $resource->adminUrl();
                $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $this->translate('[Untitled]'), 'lang' => $valueLang]) : $resource->displayTitle(null, ($valueLang));
                $media = ($resource instanceof \Omeka\Api\Representation\ItemRepresentation) ? ($resource->media()[0] ?? null) : null;
                $altText = $media ? ($media->altText() ?: $resource->displayTitle()) : $resource->displayTitle();
                $site = $resource->value('palaeostar:siteName');
                $sitename = $site -> valueResource() -> value('dcterms:title')->asHTML();
                $region = $site->valueResource() -> value('palaeostar:region')->asHTML();
                $siteandregion = '';
                $siteandregion .= $sitename;
                if (strlen($region)){
                    $siteregiontext = '';
                    $siteregiontext .= $region;
                }
                if(isset($vals['palaeostar:museum'])){
                    $museumspan = '';
                    $museumspan .= '<span>'.$vals['palaeostar:museum']['values'][0] -> value().' :</span>';
                }

                ?>

                <li class="resource <?= $resourceType ?>">
                        <?php $resourceThumbnail = $thumbnail($resource, 'medium'); ?>
                        <div class="resource-thumbnail">
                            <?php if ($resourceThumbnail): ?>
                                <?= $hyperlink->raw($resourceThumbnail ?: $defaultThumbnail, $resourceUrl, ['class' => 'resource-link']) ?>
                            <?php endif; ?>
                        </div>

                    <div class="resource__meta">
                        <?php if (strlen($siteregiontext)): ?>
                            <div><?php echo $sitename . ', ' . $region; ?></div>
                        <?php endif; ?>
                        <?php if (strlen($museumspan)): ?>
                            <div><?php echo $museumspan ?></div>
                        <?php endif; ?>
                        <?php echo $resource->link($resource->displayTitle(null, $valueLang)); ?>
                    </div>
                    <div class="resource-body resource-metadata">

                    </div>
                </li>
            <?php endforeach; ?>
            </ul>
            </div>
        </div>
    </div>

<?php endforeach; ?>

<?php echo ($totalCount > $perPage) ? '<div class="linked-footer">' . $pagination . '</div>' : ''; ?>

</div>
