<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->inlineScript()->appendFile($this->assetUrl('js/minimasonry.min.js'));
$this->inlineScript()->appendFile($this->assetUrl('js/browse.js'));
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$plugins = $this->getHelperPluginManager();

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow) {
    $this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));

    // Regions
    $mainBlockContent = $this->resourcePageBlocks($itemSet);
    $mainHasBlocks = $mainBlockContent->hasBlocks();
    $leftSidebarBlockContent = $this->resourcePageBlocks($itemSet, 'left');
    $leftSidebarHasBlocks = $leftSidebarBlockContent->hasBlocks();
    $rightSidebarBlockContent = $this->resourcePageBlocks($itemSet, 'right');
    $rightSidebarHasBlocks = $rightSidebarBlockContent->hasBlocks();

    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
}

$layoutSetting = $this->themeSetting('browse_layout', 'grid');
$gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
$listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
$isGrid = (strpos($layoutSetting, 'grid') !== false) ? true : false;
$bodyTerm = $this->siteSetting('browse_body_property_term');
$bodyTruncate = $this->themeSetting('truncate_body_property');

if (isset($_GET['view'])) {
    if ('list' === $_GET['view']) {
        $gridState = '';
        $listState = 'disabled';
        $isGrid = false;
    } else {
        $gridState = 'disabled';
        $listState = '';
        $isGrid = true;
    }
}

$decoration = $this->themeSetting('image_decoration');
$decorationClass = '';

$customFieldList=str_replace(' ','',$this->themeSetting('CustomFieldList'));
$tagTermList=explode(",", $customFieldList);

if (is_array($decoration) && in_array('media', $decoration)) {
    $decorationClass = $isGrid ? 'decoration' : 'decoration decoration--thumbnail';
}
?>

<?php if ($itemSetShow): ?>
    <?php echo $this->ResourceTags($itemSet); ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(null, ($valueLang)), 1); ?>

    <?php if ($mainHasBlocks || $leftSidebarHasBlocks || $rightSidebarHasBlocks): ?>

        <?php
        $additionalContainerClasses = '';
        if ($mainHasBlocks && $leftSidebarHasBlocks && $rightSidebarHasBlocks) {
            $additionalContainerClasses = 'regions-container--all';
        }
        ?>

        <div class="regions-container <?php echo $additionalContainerClasses; ?>">
            <?php if ($leftSidebarHasBlocks && $blockContent = $leftSidebarBlockContent->getBlocks()): ?>
                <div class="sidebar-region sidebar-region--left">
                    <div class="metadata">
                        <?php echo $blockContent; ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($mainHasBlocks && $blockContent = $mainBlockContent->getBlocks()): ?>
                <div class="main-region">
                    <div class="metadata">
                        <?php echo $blockContent; ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($rightSidebarHasBlocks && $blockContent = $rightSidebarBlockContent->getBlocks()): ?>
                <div class="sidebar-region sidebar-region--right">
                    <div class="metadata">
                        <?php echo $blockContent; ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>

    <?php endif; ?>

    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php if (strpos($layoutSetting, 'toggle') !== false): ?>
        <div class="layout-toggle">
            <button type="button" aria-label="<?php echo $translate('Grid'); ?>" title="<?php echo $translate('Grid'); ?>" class="grid icon-btn o-icon-grid" <?php echo $gridState; ?>></button>
            <button type="button" aria-label="<?php echo $translate('List'); ?>" title="<?php echo $translate('List'); ?>" class="list icon-btn o-icon-list" <?php echo $listState; ?>></button>
        </div>
    <?php endif; ?>
    <?php echo $this->browse()->renderSortSelector('items'); ?>
    <div class="advanced-search-container">
        <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    </div>
</div>

<?php $this->trigger('view.browse.before'); ?>

<ul class="resources <?php echo ($isGrid) ? 'resource-grid' : 'resource-list'; ?>">

    <?php
    foreach ($items as $item):
        $body = $bodyTerm ? $item->value($bodyTerm, ['lang' => ($valueLang)]) : $item->displayDescription(null, ($valueLang));
        $media = $item->primaryMedia();
        $altText = $media ? ($media->altText() ?: $item->displayTitle()) : $item->displayTitle();
        $thumbnail = $this->thumbnail($item, 'large', ['alt' => $altText]);
        $vals = $item->values();
        $tagTerms = $tagTermList;
        $showLabel = true;
        $template = $item->resourceTemplate();
        $tagHtml = '';
        $searchEngine=$this->themeSetting('searchController') ;

        foreach ($tagTerms as $tagTerm) {
            if(isset($vals[$tagTerm])) {
                $tagLabel="";
                $fields = $vals[$tagTerm]['values'];

                //PV 2023-11-05: This piece of code gets the resource template for the current field.
                $templateProperty = $template ? $template->resourceTemplateProperty($fields[0]->property()->id()) : null;
                $altLabel = $templateProperty ? $templateProperty->alternateLabel() : null;

                if(($fields!=null)&&(count($fields))) {
                    $tagHtml .= '<div class="tag-group ' . str_replace(':', '\:', $tagTerm) . '">';

                    if($showLabel) {
                        $label = $fields[0]->property()->label();
                        $label = $altLabel?$altLabel:$label;
                        $tagLabel=$label;
                        $tagHtml .= '<span class="tag-label">'.$tagLabel.'</span>:&nbsp;';
                    }

                    foreach ($fields as $val) {
                        try {
                            $test='';
                            $f_id = $val->property()->id();
                            $f_pid = $val->property()->label();
                            $f_pid2= $val->property()->localName();
                            $tt2=str_replace(':', '_', $tagTerm);
                            if($val)
                            {
                              // The displayName for all other tagTerms is in the default class method for value (= root of $val)
                                    // Query to make the field browsable with a link
                                    $query = ['query' => [$searchEngine => '', 'property[0][property]' => $f_id, 'property[0][type]' => 'eq', 'property[0][text]' => strval($val)]];
                                    $tagHtml .= $this->hyperlink(strval($val), $this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], $query, true), ['class' => 'tag'])." ";
                            }
                        } catch (\Throwable $th) {
                            echo $th;
                        }
                    }

                    $tagHtml .= '</div>';
                }
            }
        }
        // END custom feature 'Custom field values in search results'

        ?>
        <li class="item resource <?php echo ($isGrid) ? '' : 'media-object'; ?>">
            <!-- Thumbnail -->
            <?php if ($thumbnail): ?>
                <div class="resource__thumbnail <?php echo $decorationClass; ?>">
                    <?php echo $item->linkRaw($thumbnail); ?>
                </div>
            <?php endif; ?>

            <!-- Content -->
            <div class="resource__content">
                <?php echo $this->ResourceTags($item); ?>
                <!-- Metadata -->
                <div class="resource__meta <?php echo ($isGrid) ? '' : 'media-object-section'; ?>">
                    <?php echo $item->link($item->displayTitle(null, $valueLang)); ?>
                    <?php if (strlen($tagHtml)||strlen($body)): ?>
                        <div class="description">
                            <?php //$body contains site or resource item description. ?>
                            <?php if (strlen($body)): ?>
                                <?php echo $escape($body); ?>
                            <?php endif;?>
                            <?= $tagHtml ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </li>
    <?php endforeach; ?>

</ul>

<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php $this->trigger('view.browse.after'); ?>

<?php echo $this->pagination(); ?>
